In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Import Plotting Libararies
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

# Model Evaluation Libraries
from sklearn.metrics import classification_report, confusion_matrix

In [8]:
#expanding the dispay of text sms column
pd.set_option('display.max_colwidth', -1)

dataset = pd.read_csv("../data/full_dataset.csv")
dataset.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  


result  \
0  1        
1  1        
2  1        
3  0        
4  0        

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

In [3]:
dataset.columns

Index(['result', 'tokenized'], dtype='object')

In [5]:
data = dataset[['tokenized', 'result']]

In [25]:
# Combining all the above stundents 
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")


import sqlite3
import pandas as pd
import numpy as np
import nltk
import string
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import roc_curve, auc
from nltk.stem.porter import PorterStemmer

import re
# Tutorial about Python regular expressions: https://pymotw.com/2/re/
import string
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem.wordnet import WordNetLemmatizer

from gensim.models import Word2Vec
from gensim.models import KeyedVectors
import pickle

from tqdm import tqdm
import os
from bs4 import BeautifulSoup

import re

def decontracted(phrase):
    # specific
    phrase = re.sub(r"won't", "will not", phrase)
    phrase = re.sub(r"can\'t", "can not", phrase)

    # general
    phrase = re.sub(r"n\'t", " not", phrase)
    phrase = re.sub(r"\'re", " are", phrase)
    phrase = re.sub(r"\'s", " is", phrase)
    phrase = re.sub(r"\'d", " would", phrase)
    phrase = re.sub(r"\'ll", " will", phrase)
    phrase = re.sub(r"\'t", " not", phrase)
    phrase = re.sub(r"\'ve", " have", phrase)
    phrase = re.sub(r"\'m", " am", phrase)
    return phrase


stopwords= set(['br', 'the', 'i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've",\
            "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', \
            'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their',\
            'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', \
            'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', \
            'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', \
            'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after',\
            'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further',\
            'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more',\
            'most', 'other', 'some', 'such', 'only', 'own', 'same', 'so', 'than', 'too', 'very', \
            's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', \
            've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn',\
            "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn',\
            "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", \
            'won', "won't", 'wouldn', "wouldn't"])

preprocessed_reviews = []
# tqdm is for printing the status bar
for sentance in tqdm(dataset['tokenized'].values):
    sentance = re.sub(r"http\S+", "", sentance)
    sentance = BeautifulSoup(sentance, 'lxml').get_text()
    sentance = decontracted(sentance)
    sentance = re.sub("\S*\d\S*", "", sentance).strip()
    sentance = re.sub('[^A-Za-z]+', ' ', sentance)
    sentance = re.sub(r'\d', '', sentance)
    # https://gist.github.com/sebleier/554280
    sentance = ' '.join(e.lower() for e in sentance.split() if e.lower() not in stopwords and not e.isnumeric())
    preprocessed_reviews.append(sentance.strip())

100%|██████████| 1935/1935 [00:01<00:00, 1192.60it/s]


In [26]:
# create dataset
X = data['tokenized']
Y = data['result']
print(X.shape)
print(Y.shape)



(1935,)
(1935,)


# Feature Extration Using Bag of Words Model

In [27]:
#BoW
vectorizer = CountVectorizer() #in scikit-learn
X_bow = vectorizer.fit(preprocessed_reviews)
print("some feature names ", vectorizer.get_feature_names()[:10])
print('='*50)

final_counts = vectorizer.transform(preprocessed_reviews)
print("the type of count vectorizer ",type(final_counts))
print("the shape of out text BOW vectorizer ",final_counts.get_shape())
print("the number of unique words ", final_counts.get_shape()[1])


some feature names  ['aa', 'aaaand', 'aaj', 'aal', 'aamer', 'aap', 'aaps', 'aaron', 'aba', 'ababa']
the type of count vectorizer  <class 'scipy.sparse.csr.csr_matrix'>
the shape of out text BOW vectorizer  (1935, 44721)
the number of unique words  44721


In [28]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(stop_words='english')
X_bow = vectorizer.fit_transform(X)

In [29]:
analyze = vectorizer.build_analyzer()


In [30]:
vectorizer.get_feature_names()


['0002am',
 '0004',
 '001',
 '0024hrs',
 '0028',
 '0031hrs',
 '009',
 '01',
 '010',
 '02',
 '0207',
 '02c',
 '03',
 '04',
 '044',
 '05',
 '0561553gnlfw200505jfch7dwmp3',
 '06',
 '0619',
 '07810',
 '08',
 '0800',
 '0800555111',
 '0827',
 '0925hrs',
 '10',
 '100',
 '1000',
 '10000',
 '100000',
 '10000kg',
 '1000km',
 '1000page',
 '1001',
 '1007',
 '100acre',
 '100anight',
 '100ayear',
 '100bn',
 '100ft',
 '100g',
 '100km',
 '100m',
 '100million',
 '100ml',
 '100mph',
 '100percent',
 '100plus',
 '100th',
 '100year',
 '101',
 '10100',
 '1010wins',
 '1011',
 '101311',
 '1013ft',
 '1014',
 '1014am',
 '1015mph',
 '1015pm',
 '10160',
 '1017',
 '1017am',
 '1018',
 '101st',
 '102',
 '102000',
 '1020cm',
 '1024',
 '1025f',
 '10278',
 '103',
 '1030',
 '10300',
 '1030am',
 '1030pm',
 '104',
 '1040',
 '10400',
 '10405',
 '1040pm',
 '1045',
 '1045pm',
 '1048am',
 '1049am',
 '104th',
 '105',
 '1050',
 '10500',
 '105000',
 '1050am',
 '1051am',
 '105am',
 '105pm',
 '106',
 '106000',
 '10643',
 '106m',
 

In [31]:
X_bow.toarray()
X_bow.shape

(1935, 47155)

# Feature Extraction Using TfIDF

In [32]:
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer(smooth_idf=False)
transformer

TfidfTransformer(smooth_idf=False)

In [33]:
tf_idf_vec = TfidfVectorizer(ngram_range=(1,2), min_df=10)
tf_idf_vec.fit(preprocessed_reviews)
print("some sample features(unique words in the corpus)",tf_idf_vec.get_feature_names()[0:10])
print('='*50)

tf_idf_data = tf_idf_vec.transform(preprocessed_reviews)
print("the type of count vectorizer ",type(tf_idf_data))
print("the shape of out text TFIDF vectorizer ",tf_idf_data.get_shape())
print("the number of unique words including both unigrams and bigrams ", tf_idf_data.get_shape()[1])

some sample features(unique words in the corpus) ['aaron', 'abandon', 'abandoned', 'abandoning', 'abducted', 'ability', 'ablaze', 'able', 'able get', 'aboard']
the type of count vectorizer  <class 'scipy.sparse.csr.csr_matrix'>
the shape of out text TFIDF vectorizer  (1935, 10031)
the number of unique words including both unigrams and bigrams  10031


In [34]:
#create dataframe
tf_idf_dataframe=pd.DataFrame(tf_idf_data.toarray(),columns = tf_idf_vec.get_feature_names())
print(tf_idf_dataframe)
print("\n")

         aaron  abandon  abandoned  abandoning  abducted  ability  ablaze  \
0     0.000000  0.0      0.0        0.000000    0.0       0.0      0.0      
1     0.051835  0.0      0.0        0.000000    0.0       0.0      0.0      
2     0.000000  0.0      0.0        0.000000    0.0       0.0      0.0      
3     0.000000  0.0      0.0        0.000000    0.0       0.0      0.0      
4     0.000000  0.0      0.0        0.000000    0.0       0.0      0.0      
...        ...  ...      ...             ...    ...       ...      ...      
1930  0.000000  0.0      0.0        0.000000    0.0       0.0      0.0      
1931  0.000000  0.0      0.0        0.000000    0.0       0.0      0.0      
1932  0.000000  0.0      0.0        0.023401    0.0       0.0      0.0      
1933  0.000000  0.0      0.0        0.000000    0.0       0.0      0.0      
1934  0.000000  0.0      0.0        0.000000    0.0       0.0      0.0      

          able  able get  aboard  ...  youth  youths  youtube  youve  \
0  

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

#without smooth IDF
print("Without Smoothing:")
#define tf-idf
tf_idf_vec = TfidfVectorizer(use_idf=True, 
                        smooth_idf=False,  
                        ngram_range=(1,1), stop_words='english') # to use only  bigrams ngram_range=(2,2)
#transform
tf_idf_data = tf_idf_vec.fit_transform(X)
 
#create dataframe
tf_idf_dataframe=pd.DataFrame(tf_idf_data.toarray(),columns = tf_idf_vec.get_feature_names())
print(tf_idf_dataframe)
print("\n")
 
#with smooth

tf_idf_vec_smooth = TfidfVectorizer(use_idf=True,  
                        smooth_idf=True,  
                        ngram_range=(1,1),stop_words='english')
tf_idf_data_smooth = tf_idf_vec_smooth.fit_transform(X)
print("With Smoothing:")
tf_idf_dataframe_smooth = pd.DataFrame(tf_idf_data_smooth.toarray(),columns=tf_idf_vec_smooth.get_feature_names())
print(tf_idf_dataframe_smooth)

Without Smoothing:
      0002am  0004  001  0024hrs  0028  0031hrs  009   01  010   02  ...  \
0     0.0     0.0   0.0  0.0      0.0   0.0      0.0  0.0  0.0  0.0  ...   
1     0.0     0.0   0.0  0.0      0.0   0.0      0.0  0.0  0.0  0.0  ...   
2     0.0     0.0   0.0  0.0      0.0   0.0      0.0  0.0  0.0  0.0  ...   
3     0.0     0.0   0.0  0.0      0.0   0.0      0.0  0.0  0.0  0.0  ...   
4     0.0     0.0   0.0  0.0      0.0   0.0      0.0  0.0  0.0  0.0  ...   
...   ...     ...   ...  ...      ...   ...      ...  ...  ...  ...  ...   
1930  0.0     0.0   0.0  0.0      0.0   0.0      0.0  0.0  0.0  0.0  ...   
1931  0.0     0.0   0.0  0.0      0.0   0.0      0.0  0.0  0.0  0.0  ...   
1932  0.0     0.0   0.0  0.0      0.0   0.0      0.0  0.0  0.0  0.0  ...   
1933  0.0     0.0   0.0  0.0      0.0   0.0      0.0  0.0  0.0  0.0  ...   
1934  0.0     0.0   0.0  0.0      0.0   0.0      0.0  0.0  0.0  0.0  ...   

      zygmunt   zyprexa  zzzzz  zürich  árainn  édith  éric  özersay

# Feature Extraction Using Bigrams and Trigrams

In [36]:
c_vec = CountVectorizer(stop_words='english', ngram_range=(2,2))
# matrix of ngrams
ngrams = c_vec.fit_transform(X)
# count frequency of ngrams
count_values = ngrams.toarray().sum(axis=0)
# list of ngrams
vocab = c_vec.vocabulary_
X_2gram  = pd.DataFrame(sorted([(count_values[i],k) for k,i in vocab.items()], reverse=True)
            ).rename(columns={0: 'frequency', 1:'unigram/bigram'})

X_2gram

frequency  unigram/bigram
0       609        white house   
1       570        united states 
2       501        new york      
3       447        mr trump      
4       418        prime minister
...     ...                   ...
555949  1          0028 crews    
555950  1          0024hrs police
555951  1          001 war       
555952  1          0004 vote     
555953  1          0002am passes 

[555954 rows x 2 columns]

In [37]:
c_vec = CountVectorizer(stop_words='english', ngram_range=(3,3))
# matrix of ngrams
ngrams = c_vec.fit_transform(X)
# count frequency of ngrams
count_values = ngrams.toarray().sum(axis=0)
# list of ngrams
vocab = c_vec.vocabulary_
X_3gram = pd.DataFrame(sorted([(count_values[i],k) for k,i in vocab.items()], reverse=True)
            ).rename(columns={0: 'frequency', 1:'bigram/trigram'})

X_3gram 

frequency              bigram/trigram
0       136        president donald trump    
1       82         new york city             
2       58         speaker nancy pelosi      
3       50         special counsel robert    
4       49         quid pro quo              
...     ..                  ...              
692327  1          0028 crews dagenham       
692328  1          0024hrs police responded  
692329  1          001 war terror            
692330  1          0004 vote making          
692331  1          0002am passes breathalyser

[692332 rows x 2 columns]

# Binary Classification using TFIDF vectors

In [38]:
#Naïve Bayes, Logistic Regression, Random Forest, SVM, Perceptron

In [80]:
# Machine Learning Models
from sklearn import svm  
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import Perceptron
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
import xgboost as xgb
from sklearn.feature_extraction.text import CountVectorizer

In [40]:
# split into train test sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33)
print('Shape of X_train', X_train.shape)
print('Shape of X_test', X_test.shape)
print('Shape of Y_train', y_train.shape)
print('Shape of Y_test', y_test.shape)

Shape of X_train (1296,)
Shape of X_test (639,)
Shape of Y_train (1296,)
Shape of Y_test (639,)


In [41]:
max_feature_num = 3468
vectorizer = TfidfVectorizer(max_features=max_feature_num)
train_vecs = vectorizer.fit_transform(X_train)
test_vecs = TfidfVectorizer(max_features=max_feature_num, vocabulary=vectorizer.vocabulary_).fit_transform(X_test)

In [42]:
def NB_classifier(train_vecs, y_train, test_vecs, y_test):
    # Training
    GB = GaussianNB()
    GB.fit(train_vecs, y_train)

    # testing
    test_predictionGB = GB.predict(test_vecs)
    return classification_report(test_predictionGB, y_test) , confusion_matrix(test_predictionGB, y_test)


In [43]:
def LR_classifier(train_vecs, y_train, test_vecs, y_test):
    # Training
    LR = LogisticRegression()
    LR.fit(train_vecs, y_train)

    # testing
    test_predictionLR = LR.predict(test_vecs)
    return classification_report(test_predictionLR, y_test) , confusion_matrix(test_predictionLR, y_test)



In [44]:
def RF_classifier(train_vecs, y_train, test_vecs, y_test):
    # Training
    RF = RandomForestClassifier(n_estimators = 450, max_depth=9, random_state=43)
    RF.fit(train_vecs, y_train)

    # Testing
    test_predictionRF = RF.predict( test_vecs )
    return classification_report(test_predictionRF, y_test), confusion_matrix(test_predictionRF, y_test)

In [45]:
def SVM_classifier(train_vecs, y_train, test_vecs, y_test):
    # Training
    SVM = svm.LinearSVC(max_iter=100)
    SVM.fit(train_vecs, y_train)

    # Testing
    test_predictionSVM = SVM.predict(test_vecs)
    return classification_report(test_predictionSVM, y_test), confusion_matrix(test_predictionSVM, y_test)

In [46]:
def Perceptron_classifier(train_vecs, y_train, test_vecs, y_test):

    # Training
    Per = Perceptron(tol=1e-3, random_state=0)
    Per.fit(train_vecs, y_train)

    # Testing
    test_predictionPer = Per.predict(test_vecs)
    return classification_report(test_predictionPer, y_test), confusion_matrix(test_predictionPer, y_test)


In [70]:
def KNN_classifier(train_vecs, y_train, test_vecs, y_test):
    # Training
    KNN = KNeighborsClassifier()
    KNN.fit(train_vecs, y_train)

    # testing
    test_predictionKNN = KNN.predict(test_vecs)
    return classification_report(test_predictionKNN, y_test), confusion_matrix(test_predictionKNN, y_test)


In [71]:
def DT_classifier(train_vecs, y_train, test_vecs, y_test):
    # Training
    DT = DecisionTreeClassifier()
    DT.fit(train_vecs, y_train)

    # testing
    test_predictionDT = DT.predict(test_vecs)
    return classification_report(test_predictionDT, y_test), confusion_matrix(test_predictionDT, y_test)


In [83]:
def XGB_classifier(train_vecs, y_train, test_vecs, y_test):
    # Training

    XGB = xgb.XGBClassifier(objective="binary:logistic", random_state=42, eval_metric="auc")
    XGB.fit(train_vecs, y_train)

    # testing
    test_predictionXGB = XGB.predict(test_vecs)
    return classification_report(test_predictionXGB, y_test), confusion_matrix(test_predictionXGB, y_test)


# Results

In [47]:
class_report , conf_matrix = SVM_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of SVM CLASSIFIER on TF-IDF Vectorizer\n')
print(class_report)
print(conf_matrix)


Results of SVM CLASSIFIER on TF-IDF Vectorizer

              precision    recall  f1-score   support

           0       0.77      0.76      0.77       313
           1       0.77      0.78      0.78       326

    accuracy                           0.77       639
   macro avg       0.77      0.77      0.77       639
weighted avg       0.77      0.77      0.77       639

[[239  74]
 [ 72 254]]


In [48]:
class_report , conf_matrix = LR_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of Logistic Regression Classifier on TF-IDF Vectorizer\n')
print(class_report)
print(conf_matrix)

Results of Logistic Regression Classifier on TF-IDF Vectorizer

              precision    recall  f1-score   support

           0       0.76      0.79      0.77       301
           1       0.80      0.78      0.79       338

    accuracy                           0.78       639
   macro avg       0.78      0.78      0.78       639
weighted avg       0.78      0.78      0.78       639

[[237  64]
 [ 74 264]]


In [49]:
class_report , conf_matrix = RF_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of  Random Forest on TF-IDF Vectorizer\n')
print(class_report)
print(conf_matrix)

Results of  Random Forest on TF-IDF Vectorizer

              precision    recall  f1-score   support

           0       0.82      0.75      0.78       340
           1       0.74      0.81      0.77       299

    accuracy                           0.78       639
   macro avg       0.78      0.78      0.78       639
weighted avg       0.78      0.78      0.78       639

[[254  86]
 [ 57 242]]


In [50]:
class_report , conf_matrix = NB_classifier(train_vecs.todense(), y_train, test_vecs.todense(), y_test)
print('Results of Naive Bayes Classifier on TF-IDF Vectorizer\n')
print(class_report)
print(conf_matrix)

Results of Naive Bayes Classifier on TF-IDF Vectorizer

              precision    recall  f1-score   support

           0       0.73      0.71      0.72       321
           1       0.71      0.74      0.72       318

    accuracy                           0.72       639
   macro avg       0.72      0.72      0.72       639
weighted avg       0.72      0.72      0.72       639

[[227  94]
 [ 84 234]]


In [95]:
#class_report , conf_matrix = Perceptron_classifier(train_vecs, y_train, test_vecs, y_test)
#print('Results of Perceptron Classifier on TF-IDF Vectorizer\n')
#print(class_report)
#print(conf_matrix)

In [76]:
class_report , conf_matrix = KNN_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of KNN_classifier on TF-IDF Vectorizer\n')
print(class_report)
print(conf_matrix)

Results of KNN_classifier on TF-IDF Vectorizer

              precision    recall  f1-score   support

           0       1.00      0.49      0.65       639
           1       0.00      0.00      0.00         0

    accuracy                           0.49       639
   macro avg       0.50      0.24      0.33       639
weighted avg       1.00      0.49      0.65       639

[[311 328]
 [  0   0]]


In [77]:
class_report , conf_matrix = DT_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of Decision tree classifier on TF-IDF Vectorizer\n')
print(class_report)
print(conf_matrix)

Results of Decision tree classifier on TF-IDF Vectorizer

              precision    recall  f1-score   support

           0       0.65      0.61      0.63       334
           1       0.60      0.65      0.62       305

    accuracy                           0.63       639
   macro avg       0.63      0.63      0.63       639
weighted avg       0.63      0.63      0.63       639

[[203 131]
 [108 197]]


In [84]:
class_report , conf_matrix = XGB_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of XGB classifier on TF-IDF Vectorizer\n')
print(class_report)
print(conf_matrix)

Results of XGB classifier on TF-IDF Vectorizer

              precision    recall  f1-score   support

           0       0.74      0.68      0.71       337
           1       0.67      0.73      0.70       302

    accuracy                           0.70       639
   macro avg       0.70      0.70      0.70       639
weighted avg       0.71      0.70      0.70       639

[[229 108]
 [ 82 220]]


# Binary Classification using BOW

In [85]:
vectorizer = CountVectorizer(binary=False,ngram_range=(1,1))
train_vecs = vectorizer.fit_transform(X_train)
test_vecs = vectorizer.transform(X_test)
print (train_vecs.shape, test_vecs.shape)

(1296, 38811) (639, 38811)


Note: We will only consider training dataset to define the vocabulary and use the same vocabulary to 
represent the test dataset (as test data is supposed to be hidden).

Thus we will fit our vectorizer on the training data and use it to transform the test data,

There are 8016 unique words in vocabulary.

For each review in our dataset, the Frequency of words(term-frequency) is represented through a vocabulary vector of size 8016. That’s why we have 2323 such vectors in our training-set and similarly 1145 vectors of the similar shape in our test dataset.

Note: binary=False argument means that we fill the vocabulary vector with term-frequency. If binary=True, the vocabulary vector is filled by the presence of words (1 if the word is present and 0 otherwise).



In [86]:
class_report , conf_matrix = SVM_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of SVM CLASSIFIER on BOW\n')
print(class_report)
print(conf_matrix)


Results of SVM CLASSIFIER on BOW

              precision    recall  f1-score   support

           0       0.80      0.72      0.76       347
           1       0.70      0.79      0.74       292

    accuracy                           0.75       639
   macro avg       0.75      0.75      0.75       639
weighted avg       0.76      0.75      0.75       639

[[249  98]
 [ 62 230]]


In [87]:
class_report , conf_matrix = LR_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of Logistic Regression Classifier on BOW \n')
print(class_report)
print(conf_matrix)

Results of Logistic Regression Classifier on BOW 

              precision    recall  f1-score   support

           0       0.82      0.73      0.77       346
           1       0.72      0.81      0.76       293

    accuracy                           0.77       639
   macro avg       0.77      0.77      0.77       639
weighted avg       0.77      0.77      0.77       639

[[254  92]
 [ 57 236]]


In [88]:
class_report , conf_matrix = RF_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of  Random Forest on BOW \n')
print(class_report)
print(conf_matrix)

Results of  Random Forest on BOW 

              precision    recall  f1-score   support

           0       0.83      0.70      0.76       366
           1       0.67      0.80      0.73       273

    accuracy                           0.74       639
   macro avg       0.75      0.75      0.74       639
weighted avg       0.76      0.74      0.75       639

[[257 109]
 [ 54 219]]


In [89]:
class_report , conf_matrix = NB_classifier(train_vecs.todense(), y_train, test_vecs.todense(), y_test)
print('Results of Naive Bayes Classifier on BOW \n')
print(class_report)
print(conf_matrix)

Results of Naive Bayes Classifier on BOW 

              precision    recall  f1-score   support

           0       0.48      0.79      0.60       189
           1       0.88      0.64      0.74       450

    accuracy                           0.68       639
   macro avg       0.68      0.71      0.67       639
weighted avg       0.76      0.68      0.70       639

[[149  40]
 [162 288]]


In [94]:
#class_report , conf_matrix = Perceptron_classifier(train_vecs, y_train, test_vecs, y_test)
#print('Results of Perceptron Classifier on BOW\n')
#print(class_report)
#print(conf_matrix)

In [91]:
class_report , conf_matrix = KNN_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of KNN_classifier on BOW\n')
print(class_report)
print(conf_matrix)

Results of KNN_classifier on BOW

              precision    recall  f1-score   support

           0       0.87      0.64      0.74       419
           1       0.55      0.81      0.65       220

    accuracy                           0.70       639
   macro avg       0.71      0.73      0.70       639
weighted avg       0.76      0.70      0.71       639

[[270 149]
 [ 41 179]]


In [92]:
class_report , conf_matrix = DT_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of Decision tree classifier on BOW\n')
print(class_report)
print(conf_matrix)

Results of Decision tree classifier on BOW

              precision    recall  f1-score   support

           0       0.72      0.66      0.69       339
           1       0.65      0.71      0.68       300

    accuracy                           0.69       639
   macro avg       0.69      0.69      0.69       639
weighted avg       0.69      0.69      0.69       639

[[225 114]
 [ 86 214]]


In [93]:
class_report , conf_matrix = XGB_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of XGB classifier  on BOW\n')
print(class_report)
print(conf_matrix)

Results of XGB classifier  on BOW

              precision    recall  f1-score   support

           0       0.81      0.75      0.78       333
           1       0.75      0.80      0.78       306

    accuracy                           0.78       639
   macro avg       0.78      0.78      0.78       639
weighted avg       0.78      0.78      0.78       639

[[251  82]
 [ 60 246]]


# Binary Classification using Bigram/Trigram

In [96]:
vectorizer = CountVectorizer(binary=False,ngram_range=(2,2))
train_vecs = vectorizer.fit_transform(X_train)
test_vecs = vectorizer.transform(X_test)
print (train_vecs.shape, test_vecs.shape)

(1296, 394821) (639, 394821)


In [97]:
class_report , conf_matrix = SVM_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of SVM CLASSIFIER on Bi-gram\n')
print(class_report)
print(conf_matrix)

Results of SVM CLASSIFIER on Bi-gram

              precision    recall  f1-score   support

           0       0.83      0.73      0.78       354
           1       0.71      0.81      0.76       285

    accuracy                           0.77       639
   macro avg       0.77      0.77      0.77       639
weighted avg       0.78      0.77      0.77       639

[[258  96]
 [ 53 232]]


In [98]:
class_report , conf_matrix = LR_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of Logistic Regression Classifier on Bi-gram\n')
print(class_report)
print(conf_matrix)

Results of Logistic Regression Classifier on Bi-gram

              precision    recall  f1-score   support

           0       0.86      0.72      0.78       372
           1       0.68      0.83      0.75       267

    accuracy                           0.76       639
   macro avg       0.77      0.77      0.76       639
weighted avg       0.78      0.76      0.77       639

[[266 106]
 [ 45 222]]


In [99]:
class_report , conf_matrix = RF_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of  Random Forest on Bi-gram\n')
print(class_report)
print(conf_matrix)

Results of  Random Forest on Bi-gram

              precision    recall  f1-score   support

           0       0.87      0.68      0.76       398
           1       0.61      0.83      0.70       241

    accuracy                           0.74       639
   macro avg       0.74      0.75      0.73       639
weighted avg       0.77      0.74      0.74       639

[[270 128]
 [ 41 200]]


In [100]:
class_report , conf_matrix = NB_classifier(train_vecs.todense(), y_train, test_vecs.todense(), y_test)
print('Results of Naive Bayes Classifier on Bi-gram \n')
print(class_report)
print(conf_matrix)

Results of Naive Bayes Classifier on Bi-gram 

              precision    recall  f1-score   support

           0       0.40      0.87      0.55       144
           1       0.94      0.62      0.75       495

    accuracy                           0.68       639
   macro avg       0.67      0.75      0.65       639
weighted avg       0.82      0.68      0.71       639

[[125  19]
 [186 309]]


In [101]:
#class_report , conf_matrix = Perceptron_classifier(train_vecs, y_train, test_vecs, y_test)
#print('Results of Perceptron Classifier on Bi-gram \n')
#print(class_report)
#print(conf_matrix)

In [102]:
class_report , conf_matrix = KNN_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of KNN_classifier on Bi-gram \n')
print(class_report)
print(conf_matrix)

Results of KNN_classifier on Bi-gram 

              precision    recall  f1-score   support

           0       1.00      0.49      0.66       632
           1       0.02      0.86      0.04         7

    accuracy                           0.49       639
   macro avg       0.51      0.67      0.35       639
weighted avg       0.99      0.49      0.65       639

[[310 322]
 [  1   6]]


In [103]:
class_report , conf_matrix = DT_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of Decision tree classifier on Bii-gram \n')
print(class_report)
print(conf_matrix)

Results of Decision tree classifier on Bii-gram 

              precision    recall  f1-score   support

           0       0.68      0.65      0.66       328
           1       0.65      0.68      0.66       311

    accuracy                           0.66       639
   macro avg       0.66      0.66      0.66       639
weighted avg       0.66      0.66      0.66       639

[[212 116]
 [ 99 212]]


In [104]:
class_report , conf_matrix = XGB_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of XGB classifier  on Bi-gram \n')
print(class_report)
print(conf_matrix)

Results of XGB classifier  on Bi-gram 

              precision    recall  f1-score   support

           0       0.78      0.73      0.76       333
           1       0.73      0.78      0.75       306

    accuracy                           0.76       639
   macro avg       0.76      0.76      0.76       639
weighted avg       0.76      0.76      0.76       639

[[244  89]
 [ 67 239]]


In [105]:
vectorizer = CountVectorizer(binary=False,ngram_range=(3,3))
train_vecs = vectorizer.fit_transform(X_train)
test_vecs = vectorizer.transform(X_test)
print (train_vecs.shape, test_vecs.shape)

(1296, 742164) (639, 742164)


In [106]:
class_report , conf_matrix = SVM_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of SVM CLASSIFIER on Tri-gram\n')
print(class_report)
print(conf_matrix)

Results of SVM CLASSIFIER on Tri-gram

              precision    recall  f1-score   support

           0       0.89      0.62      0.73       447
           1       0.48      0.82      0.60       192

    accuracy                           0.68       639
   macro avg       0.68      0.72      0.67       639
weighted avg       0.76      0.68      0.69       639

[[276 171]
 [ 35 157]]


In [107]:
class_report , conf_matrix = LR_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of Logistic Regression Classifier on Tri-gram\n')
print(class_report)
print(conf_matrix)

Results of Logistic Regression Classifier on Tri-gram

              precision    recall  f1-score   support

           0       0.93      0.60      0.73       477
           1       0.42      0.86      0.57       162

    accuracy                           0.67       639
   macro avg       0.67      0.73      0.65       639
weighted avg       0.80      0.67      0.69       639

[[288 189]
 [ 23 139]]


In [108]:
class_report , conf_matrix = RF_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of  Random Forest on Tri-gram\n')
print(class_report)
print(conf_matrix)

Results of  Random Forest on Tri-gram

              precision    recall  f1-score   support

           0       0.96      0.59      0.73       506
           1       0.37      0.90      0.52       133

    accuracy                           0.65       639
   macro avg       0.66      0.75      0.63       639
weighted avg       0.83      0.65      0.69       639

[[298 208]
 [ 13 120]]


In [109]:
class_report , conf_matrix = NB_classifier(train_vecs.todense(), y_train, test_vecs.todense(), y_test)
print('Results of Naive Bayes Classifier on Tri-gram \n')
print(class_report)
print(conf_matrix)

Results of Naive Bayes Classifier on Tri-gram 

              precision    recall  f1-score   support

           0       0.46      0.82      0.59       173
           1       0.91      0.64      0.75       466

    accuracy                           0.69       639
   macro avg       0.68      0.73      0.67       639
weighted avg       0.78      0.69      0.70       639

[[142  31]
 [169 297]]


In [114]:
#class_report , conf_matrix = Perceptron_classifier(train_vecs, y_train, test_vecs, y_test)
#print('Results of Perceptron Classifier on Tri-gram \n')
#print(class_report)
#print(conf_matrix)

In [111]:
class_report , conf_matrix = KNN_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of KNN_classifier on Tri-gram \n')
print(class_report)
print(conf_matrix)

Results of KNN_classifier on Tri-gram 

              precision    recall  f1-score   support

           0       1.00      0.49      0.65       639
           1       0.00      0.00      0.00         0

    accuracy                           0.49       639
   macro avg       0.50      0.24      0.33       639
weighted avg       1.00      0.49      0.65       639

[[311 328]
 [  0   0]]


In [112]:
class_report , conf_matrix = DT_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of Decision tree classifier on Tri-gram \n')
print(class_report)
print(conf_matrix)

Results of Decision tree classifier on Tri-gram 

              precision    recall  f1-score   support

           0       0.67      0.63      0.65       327
           1       0.63      0.67      0.65       312

    accuracy                           0.65       639
   macro avg       0.65      0.65      0.65       639
weighted avg       0.65      0.65      0.65       639

[[207 120]
 [104 208]]


In [113]:
class_report , conf_matrix = XGB_classifier(train_vecs, y_train, test_vecs, y_test)
print('Results of XGB classifier  on Tri-gram \n')
print(class_report)
print(conf_matrix)

Results of XGB classifier  on Tri-gram 

              precision    recall  f1-score   support

           0       0.74      0.68      0.71       337
           1       0.67      0.73      0.70       302

    accuracy                           0.70       639
   macro avg       0.70      0.70      0.70       639
weighted avg       0.71      0.70      0.70       639

[[229 108]
 [ 82 220]]
